/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RecallContainer: typeof import('./src/components/RecallContainer.vue')['default']
    RecallDataTable: typeof import('./src/components/RecallDataTable.vue')['default']
    RecallDrawer: typeof import('./src/components/RecallDrawer.vue')['default']
    RecallFilterDrawer: typeof import('./src/components/RecallFilterDrawer.vue')['default']
    RecallFilterToggle: typeof import('./src/components/RecallFilterToggle.vue')['default']
    RecallNavbar: typeof import('./src/components/RecallNavbar.vue')['default']
    RecallStrip: typeof import('./src/components/RecallStrip.vue')['default']
    RecallTitle: typeof import('./src/components/RecallTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
